FROM caddy:{{ caddy_caddy_base_version }}-builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/route53

FROM caddy:{{ caddy_caddy_base_version }}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
